---
name: linters

on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

#      - name: Lint Code Base
#        uses: github/super-linter@v4
#        env:
#          VALIDATE_ALL_CODEBASE: true
#          DEFAULT_BRANCH: main
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}